using System;
using System.Collections.Generic;

// This file is automatically generated by DataTableAssetGenerator.cs
// Do not modify this file

namespace TabbySheet
{
	[Serializable]
	public partial class FoodsTable : DataSheetBase<FoodsTable, FoodsTable.Data>
	{
		public enum UniqueKey
		{
			Id
		}

		private Dictionary<int, Data> idToData = new Dictionary<int, Data>();

		public FoodsTable() : base()
		{
			foreach(var data in datas)
				idToData.Add(data.Id, data);
		}

		[Serializable]
		public partial class Data
		{
			public int Id { get; set; }
			public string Name { get; set; }
			public int Price { get; set; }
			public bool CanBuy { get; set; }
		}

		public Data GetDataById(int id)
		{
			return idToData[id];
		}
	}
}
